import React from 'react';
import { createRoot } from 'react-dom/client';
import App from './App';
import '@fontsource/inter/400.css';
import '@fontsource/inter/500.css';
import '@fontsource/inter/600.css';
import '@fontsource/inter/700.css';
import '@fontsource/inter/800.css';
import './app.css';
createRoot(document.getElementById('root')).render(<App />);
